/** Operators are light playstyle accents. Gunplay stays primary. */

export const CHARACTERS = [
  {
    id: 'ryn',
    nameKey: 'op.ryn.name',
    roleKey: 'role.runner',
    blurbKey: 'op.ryn.blurb',
    passiveKey: 'op.ryn.passive',
    tacticalKey: 'op.ryn.tactical',
    ultimateKey: 'op.ryn.ultimate',
    tactical: { id: 'overdrive', cd: 16, duration: 3, speed: 1.28 },
    ultimate: { id: 'vector_line', duration: 6, speed: 1.38 },
    passive: { speed: 1.08, slideFriction: 0.84 },
    visual: { accent: '#5cffd6', shoulders: [0.85, 0.85], head: 'helm', back: 'sash', antenna: true, bulk: 0.92 },
  },
  {
    id: 'kael',
    nameKey: 'op.kael.name',
    roleKey: 'role.vanguard',
    blurbKey: 'op.kael.blurb',
    passiveKey: 'op.kael.passive',
    tacticalKey: 'op.kael.tactical',
    ultimateKey: 'op.kael.ultimate',
    tactical: { id: 'aegis', cd: 18, duration: 8, hp: 380 },
    ultimate: { id: 'iron_hymn', duration: 6, armor: 40, resist: 0.22 },
    passive: { armor: 15 },
    visual: { accent: '#8eb4ff', shoulders: [1.35, 1.35], head: 'helm', back: 'plate', bulk: 1.12 },
  },
  {
    id: 'lumen',
    nameKey: 'op.lumen.name',
    roleKey: 'role.scout',
    blurbKey: 'op.lumen.blurb',
    passiveKey: 'op.lumen.passive',
    tacticalKey: 'op.lumen.tactical',
    ultimateKey: 'op.lumen.ultimate',
    tactical: { id: 'ping_sweep', cd: 20, duration: 2.2, radius: 18 },
    ultimate: { id: 'lattice_eye', duration: 4, radius: 80 },
    passive: { markOnHit: 1.6 },
    visual: { accent: '#7af0ff', shoulders: [0.8, 0.8], head: 'wide', back: 'none', antenna: true, bulk: 0.9 },
  },
  {
    id: 'brassa',
    nameKey: 'op.brassa.name',
    roleKey: 'role.engineer',
    blurbKey: 'op.brassa.blurb',
    passiveKey: 'op.brassa.passive',
    tacticalKey: 'op.brassa.tactical',
    ultimateKey: 'op.brassa.ultimate',
    tactical: { id: 'pylon', cd: 22, duration: 14, hp: 140 },
    ultimate: { id: 'fortify', duration: 10, hp: 700 },
    passive: { reloadNearDeploy: 0.85 },
    visual: { accent: '#ffb03a', shoulders: [1.05, 1.05], head: 'helm', back: 'pack', bulk: 1.05 },
  },
  {
    id: 'sable',
    nameKey: 'op.sable.name',
    roleKey: 'role.striker',
    blurbKey: 'op.sable.blurb',
    passiveKey: 'op.sable.passive',
    tacticalKey: 'op.sable.tactical',
    ultimateKey: 'op.sable.ultimate',
    tactical: { id: 'blink', cd: 14, distance: 8 },
    ultimate: { id: 'shatter', duration: 0, fuse: 0.85, radius: 4.6, damage: 78 },
    passive: { dodgeDamage: 0.1, dodgeDamageTime: 2 },
    visual: { accent: '#ff5a3c', shoulders: [1.3, 0.7], head: 'helm', back: 'none', bulk: 0.98 },
  },
  {
    id: 'orrin',
    nameKey: 'op.orrin.name',
    roleKey: 'role.sentinel',
    blurbKey: 'op.orrin.blurb',
    passiveKey: 'op.orrin.passive',
    tacticalKey: 'op.orrin.tactical',
    ultimateKey: 'op.orrin.ultimate',
    tactical: { id: 'snare', cd: 18, duration: 5, radius: 4.2, slow: 0.42 },
    ultimate: { id: 'bastion_dome', duration: 6.5, radius: 4.4, hp: 420 },
    passive: { flinch: 0.45 },
    visual: { accent: '#d7c4a3', shoulders: [1.1, 1.1], head: 'helm', back: 'none', coat: true, bulk: 1.06 },
  },
  {
    id: 'nyx',
    nameKey: 'op.nyx.name',
    roleKey: 'role.ghost',
    blurbKey: 'op.nyx.blurb',
    passiveKey: 'op.nyx.passive',
    tacticalKey: 'op.nyx.tactical',
    ultimateKey: 'op.nyx.ultimate',
    tactical: { id: 'shade', cd: 16, duration: 5.5, radius: 3.6 },
    ultimate: { id: 'mirror', duration: 8, count: 2 },
    passive: { footstep: 0.38 },
    visual: { accent: '#9aa4c7', shoulders: [0.75, 0.75], head: 'hood', back: 'sash', bulk: 0.9 },
  },
  {
    id: 'tess',
    nameKey: 'op.tess.name',
    roleKey: 'role.technician',
    blurbKey: 'op.tess.blurb',
    passiveKey: 'op.tess.passive',
    tacticalKey: 'op.tess.tactical',
    ultimateKey: 'op.tess.ultimate',
    tactical: { id: 'hex_drone', cd: 18, duration: 8, radius: 16 },
    ultimate: { id: 'blackout', duration: 5, radius: 12 },
    passive: { cdMul: 0.9 },
    visual: { accent: '#c9a2ff', shoulders: [0.9, 1.15], head: 'helm', back: 'drone', bulk: 0.96 },
  },
  {
    id: 'marrow',
    nameKey: 'op.marrow.name',
    roleKey: 'role.bruiser',
    blurbKey: 'op.marrow.blurb',
    passiveKey: 'op.marrow.passive',
    tacticalKey: 'op.marrow.tactical',
    ultimateKey: 'op.marrow.ultimate',
    tactical: { id: 'slam', cd: 15, radius: 3.6, damage: 38, window: 2.2 },
    ultimate: { id: 'unbreakable', duration: 7, meleeMul: 1.45, resist: 0.18 },
    passive: { maxHp: 115 },
    visual: { accent: '#e07a4c', shoulders: [1.25, 1.25], head: 'helm', back: 'plate', bulk: 1.16 },
  },
  {
    id: 'ione',
    nameKey: 'op.ione.name',
    roleKey: 'role.vertical',
    blurbKey: 'op.ione.blurb',
    passiveKey: 'op.ione.passive',
    tacticalKey: 'op.ione.tactical',
    ultimateKey: 'op.ione.ultimate',
    tactical: { id: 'updraft', cd: 13, force: 11.2 },
    ultimate: { id: 'skyhook', duration: 7, jumpMul: 1.35, gravity: 0.72 },
    passive: { jump: 1.12, vault: 0.75 },
    visual: { accent: '#9ad7ff', shoulders: [0.8, 0.8], head: 'helm', back: 'none', antenna: true, bulk: 0.94, longLegs: true },
  },
  {
    id: 'peck',
    nameKey: 'op.peck.name',
    roleKey: 'role.support',
    blurbKey: 'op.peck.blurb',
    passiveKey: 'op.peck.passive',
    tacticalKey: 'op.peck.tactical',
    ultimateKey: 'op.peck.ultimate',
    tactical: { id: 'mend', cd: 20, duration: 5, radius: 4.2, hps: 9 },
    ultimate: { id: 'triage', duration: 0, radius: 12, heal: 40 },
    passive: { regenDelay: -1 },
    visual: { accent: '#8dffc6', shoulders: [1.0, 1.0], head: 'wide', back: 'sash', bulk: 1.0 },
  },
  {
    id: 'vesper',
    nameKey: 'op.vesper.name',
    roleKey: 'role.experimental',
    blurbKey: 'op.vesper.blurb',
    passiveKey: 'op.vesper.passive',
    tacticalKey: 'op.vesper.tactical',
    ultimateKey: 'op.vesper.ultimate',
    tactical: { id: 'phase', cd: 18, duration: 0.6 },
    ultimate: { id: 'catalog', duration: 8, fireMul: 1.12, speedMul: 1.18 },
    passive: { projectileSpeed: 1.06 },
    visual: { accent: '#ff8ad4', shoulders: [1.28, 0.72], head: 'helm', back: 'pack', bulk: 1.0, seam: true },
  },
];

export const CHARACTER_MAP = Object.fromEntries(CHARACTERS.map((c) => [c.id, c]));

export function getCharacter(id) {
  return CHARACTER_MAP[id] || CHARACTER_MAP.ryn;
}

export const DRILL_NAMES = [
  'Juno Pike', 'Ash Meridian', 'Nim Rusk', 'Pax Drum', 'Ren Solace', 'Lio Hatch',
  'Uma Crest', 'Silo Wren', 'Kade Morrow', 'Nia Pell', 'Holt Ives', 'Moss Keller',
  'Tara Venn', 'Quin Adler', 'Bea Frost', 'Ned Carrow', 'Ivy Kade', 'Cole Vanta',
  'Sera Quill', 'Orris Lane',
];
