export const MODES = [
  {
    id: 'team_fracture',
    nameKey: 'mode.team_fracture.name',
    descKey: 'mode.team_fracture.desc',
    teams: true,
    ranked: false,
    scoreLimit: 100,
    timeLimit: 7 * 60,
    respawn: 3,
    regenDelay: 4,
    regenRate: 18,
    lives: 0,
    overtime: true,
    fill: 8,
  },
  {
    id: 'free_fracture',
    nameKey: 'mode.free_fracture.name',
    descKey: 'mode.free_fracture.desc',
    teams: false,
    scoreLimit: 30,
    timeLimit: 6 * 60,
    respawn: 2.5,
    regenDelay: 4,
    regenRate: 18,
    lives: 0,
    overtime: false,
    fill: 8,
  },
  {
    id: 'dominion',
    nameKey: 'mode.dominion.name',
    descKey: 'mode.dominion.desc',
    teams: true,
    scoreLimit: 250,
    timeLimit: 8 * 60,
    respawn: 3.5,
    regenDelay: 4,
    regenRate: 16,
    lives: 0,
    overtime: true,
    fill: 8,
    zones: 3,
  },
  {
    id: 'pulsepoint',
    nameKey: 'mode.pulsepoint.name',
    descKey: 'mode.pulsepoint.desc',
    teams: true,
    scoreLimit: 250,
    timeLimit: 10 * 60,
    respawn: 3.5,
    regenDelay: 4.5,
    regenRate: 14,
    lives: 0,
    overtime: true,
    fill: 8,
    rotate: 30,
  },
  {
    id: 'core_run',
    nameKey: 'mode.core_run.name',
    descKey: 'mode.core_run.desc',
    teams: true,
    scoreLimit: 3,
    timeLimit: 8 * 60,
    respawn: 4,
    regenDelay: 5,
    regenRate: 12,
    lives: 0,
    overtime: true,
    fill: 8,
  },
  {
    id: 'last_circuit',
    nameKey: 'mode.last_circuit.name',
    descKey: 'mode.last_circuit.desc',
    teams: true,
    scoreLimit: 6,
    timeLimit: 12 * 60,
    roundTime: 80,
    respawn: 0,
    regenDelay: 99,
    regenRate: 0,
    lives: 1,
    overtime: false,
    fill: 8,
  },
  {
    id: 'arsenal_march',
    nameKey: 'mode.arsenal_march.name',
    descKey: 'mode.arsenal_march.desc',
    teams: false,
    scoreLimit: 16,
    timeLimit: 8 * 60,
    respawn: 2.2,
    regenDelay: 3.5,
    regenRate: 20,
    lives: 0,
    overtime: false,
    fill: 8,
  },
  {
    id: 'ranked_circuit',
    nameKey: 'mode.ranked_circuit.name',
    descKey: 'mode.ranked_circuit.desc',
    teams: true,
    ranked: true,
    scoreLimit: 75,
    timeLimit: 9 * 60,
    respawn: 3.5,
    regenDelay: 99,
    regenRate: 0,
    lives: 0,
    overtime: true,
    fill: 8,
    lockLoadout: true,
  },
  {
    id: 'practice',
    nameKey: 'mode.practice.name',
    descKey: 'mode.practice.desc',
    teams: false,
    scoreLimit: 0,
    timeLimit: 0,
    respawn: 0.4,
    regenDelay: 0.4,
    regenRate: 80,
    lives: 0,
    overtime: false,
    fill: 1,
    practice: true,
  },
  {
    id: 'tutorial',
    nameKey: 'mode.tutorial.name',
    descKey: 'mode.tutorial.desc',
    teams: false,
    scoreLimit: 0,
    timeLimit: 0,
    respawn: 0.4,
    regenDelay: 0.3,
    regenRate: 80,
    lives: 0,
    overtime: false,
    fill: 1,
    practice: true,
    tutorial: true,
  },
];

export const MODE_MAP = Object.fromEntries(MODES.map((m) => [m.id, m]));

export function getMode(id) {
  return MODE_MAP[id] || MODE_MAP.team_fracture;
}

export function resolveRules(modeId, overrides = {}) {
  const mode = getMode(modeId);
  return {
    modeId: mode.id,
    teams: mode.teams,
    ranked: !!mode.ranked,
    scoreLimit: mode.scoreLimit,
    timeLimit: mode.timeLimit,
    roundTime: mode.roundTime || 0,
    respawn: mode.respawn,
    regenDelay: mode.regenDelay,
    regenRate: mode.regenRate,
    lives: mode.lives,
    overtime: mode.overtime,
    rotate: mode.rotate || 0,
    lockLoadout: !!mode.lockLoadout,
    practice: !!mode.practice,
    tutorial: !!mode.tutorial,
    friendlyFire: false,
    abilities: true,
    moveSpeed: 1,
    gravity: 1,
    health: 100,
    armor: 0,
    fallDamage: false,
    weaponPool: null,
    fillBots: true,
    botDifficulty: 'normal',
    ...overrides,
  };
}

export const QUICK_CHAT = [
  'chat.move', 'chat.spotted', 'chat.help', 'chat.cover',
  'chat.objective', 'chat.nice', 'chat.reloading', 'chat.ult',
];
