/** Every user-facing string. Keys are stable; add languages without touching gameplay code. */
export const STRINGS = {
  "nav.compete": {"en": "Compete", "it": "Competi"},
  "nav.operator": {"en": "Your operator", "it": "Il tuo operatore"},
  "nav.community": {"en": "Community", "it": "Community"},
  "nav.system": {"en": "System", "it": "Sistema"},
  "home.title": {"en": "BREAK THE LINE.", "it": "SPEZZA LA LINEA."},
  "home.desc": {"en": "Fast fights. Sharp instincts. Your next circuit starts here.", "it": "Scontri rapidi. Riflessi pronti. Il tuo prossimo circuito inizia qui."},
  "home.ready": {"en": "Operator ready", "it": "Operatore pronto"},
  "home.edit": {"en": "Edit loadout", "it": "Modifica equipaggiamento"},
  "home.range": {"en": "Firing range", "it": "Poligono"},
  "home.setup": {"en": "Your next circuit", "it": "Il prossimo circuito"},
  "home.setup_hint": {"en": "Pick your fight. Make it yours.", "it": "Scegli la tua sfida. Falla tua."},
  "home.options": {"en": "Team & match options", "it": "Squadra e opzioni partita"},
  "home.local_hint": {"en": "Instant play · No queue · Local simulation", "it": "Gioca subito · Nessuna coda · Simulazione locale"},
  "home.relay_hint": {"en": "Online match · Server-authoritative combat", "it": "Partita online · Combattimento gestito dal server"},
  "controls.hint": {"en": "Move the mouse to look. Left click to fire, right click to aim. Esc releases the cursor and opens the pause menu.", "it": "Muovi il mouse per guardare. Clic sinistro per sparare, destro per mirare. Esc libera il cursore e apre il menu di pausa."},
  "controls.lock_error": {"en": "Click Resume to capture the mouse. If blocked, allow pointer lock in your browser or open the game outside the embedded preview.", "it": "Clicca Riprendi per catturare il mouse. Se bloccato, consenti il blocco del puntatore nel browser o apri il gioco fuori dall’anteprima incorporata."},
  "controls.paused": {"en": "Take a breather.", "it": "Prendi fiato."},
  "settings.controls": {"en": "Controls", "it": "Controlli"},
  "settings.gameplay": {"en": "Gameplay", "it": "Gioco"},
  "settings.video": {"en": "Video", "it": "Video"},
  "settings.audio": {"en": "Audio", "it": "Audio"},
  "settings.bindings": {"en": "Key bindings", "it": "Assegnazione tasti"},
  "settings.mouse": {"en": "Mouse & camera", "it": "Mouse e visuale"},
  "settings.controller": {"en": "Controller", "it": "Controller"},
  "settings.saved": {"en": "Saved automatically", "it": "Salvataggio automatico"},
  "settings.hold_aim": {"en": "Hold to aim (off = toggle)", "it": "Tieni premuto per mirare (off = alterna)"},
  "settings.toggle_crouch": {"en": "Toggle crouch", "it": "Accovacciamento alternato"},
  "settings.auto_sprint": {"en": "Auto sprint", "it": "Scatto automatico"},
  "settings.bind_hint": {"en": "Select an action, then press a key or mouse button.", "it": "Seleziona un’azione, poi premi un tasto o un pulsante del mouse."},
  "settings.reset_bindings": {"en": "Restore default bindings", "it": "Ripristina i tasti predefiniti"},

  "meta.title": { en: "VECTORBREAK", it: "VECTORBREAK" },
  "meta.tagline": { en: "Break the line. Own the lattice.", it: "Spezza la linea. Domina il reticolo." },
  "meta.loading": { en: "Linking lattice…", it: "Collegamento al reticolo…" },
  "meta.tip1": { en: "Sprint, then crouch, to drift. Jump out of a drift to keep your speed.", it: "Scatta, poi accovacciati, per scivolare. Salta durante la scivolata per tenere la velocità." },
  "meta.tip2": { en: "Recoil patterns are learnable. Pull against the kick.", it: "Il rinculo è prevedibile. Contrasta il calcio dell'arma." },
  "meta.tip3": { en: "Abilities open fights. Guns finish them.", it: "Le abilità aprono gli scontri. Le armi li chiudono." },
  "meta.tip4": { en: "Swap shoulders with C when a corner blocks your view.", it: "Cambia spalla con C se un angolo ti copre la visuale." },
  "meta.tip5": { en: "Objectives pay more than a lonely elimination.", it: "Gli obiettivi pagano più di un'eliminazione isolata." },
  "meta.click": { en: "Click to deploy", it: "Clicca per schierarti" },
  "meta.webgl": { en: "WebGL is unavailable in this browser.", it: "WebGL non è disponibile in questo browser." },

  "menu.play": { en: "Play", it: "Gioca" },
  "menu.mode_info": { en: "How it works", it: "Come funziona" },
  "menu.quick": { en: "Quick circuit", it: "Circuito rapido" },
  "menu.ranked": { en: "Ranked", it: "Classificata" },
  "menu.loadout": { en: "Loadout", it: "Equipaggiamento" },
  "menu.operators": { en: "Characters", it: "Personaggi" },
  "menu.armory": { en: "Weapons", it: "Armi" },
  "menu.customize": { en: "Customize", it: "Personalizza" },
  "menu.practice": { en: "Practice", it: "Allenamento" },
  "menu.custom": { en: "Custom match", it: "Partita privata" },
  "menu.profile": { en: "Profile", it: "Profilo" },
  "menu.leaderboards": { en: "Leaderboards", it: "Classifiche" },
  "menu.settings": { en: "Settings", it: "Impostazioni" },
  "menu.social": { en: "Social", it: "Social" },
  "menu.editor": { en: "Lattice editor", it: "Editor reticolo" },
  "menu.replays": { en: "Replays", it: "Replay" },
  "menu.tutorial": { en: "Tutorial", it: "Tutorial" },
  "menu.exit": { en: "Exit", it: "Esci" },
  "menu.back": { en: "Back", it: "Indietro" },
  "menu.close": { en: "Close", it: "Chiudi" },
  "menu.apply": { en: "Apply", it: "Applica" },
  "menu.reset": { en: "Reset", it: "Reimposta" },
  "menu.save": { en: "Save", it: "Salva" },
  "menu.cancel": { en: "Cancel", it: "Annulla" },
  "menu.confirm": { en: "Confirm", it: "Conferma" },
  "menu.offline": { en: "Local lattice", it: "Reticolo locale" },
  "menu.online": { en: "Dedicated relay", it: "Nodo dedicato" },
  "menu.lowspec": { en: "Low-spec mode", it: "Modalità leggera" },
  "menu.how": { en: "How to play", it: "Come si gioca" },
  "menu.dismiss": { en: "Got it", it: "Capito" },
  "menu.language": { en: "Language", it: "Lingua" },
  "menu.english": { en: "English", it: "English" },
  "menu.italian": { en: "Italiano", it: "Italiano" },
  "menu.exit_hint": { en: "Close this tab to leave Vectorbreak.", it: "Chiudi questa scheda per uscire da Vectorbreak." },
  "menu.version": { en: "Season 1 · First Lattice", it: "Stagione 1 · Primo Reticolo" },

  "play.mode": { en: "Mode", it: "Modalità" },
  "play.map": { en: "Map", it: "Mappa" },
  "play.random": { en: "Random lattice", it: "Reticolo casuale" },
  "play.fill": { en: "Fill with drills", it: "Riempi con i Drill" },
  "play.difficulty": { en: "Drill difficulty", it: "Difficoltà Drill" },
  "play.region": { en: "Region", it: "Regione" },
  "play.party": { en: "Party", it: "Gruppo" },
  "play.search": { en: "Searching the lattice", it: "Ricerca nel reticolo" },
  "play.found": { en: "Circuit found", it: "Circuito trovato" },
  "play.cancel": { en: "Cancel search", it: "Annulla ricerca" },
  "play.ping": { en: "Ping", it: "Ping" },
  "play.skill": { en: "Skill band", it: "Fascia di abilità" },
  "play.start": { en: "Deploy", it: "Schierati" },
  "play.again": { en: "Play again", it: "Rigioca" },
  "play.leave": { en: "Leave match", it: "Abbandona" },
  "play.resume": { en: "Resume", it: "Riprendi" },
  "play.score": { en: "Scoreboard", it: "Tabellone" },

  "diff.beginner": { en: "Beginner", it: "Principiante" },
  "diff.easy": { en: "Easy", it: "Facile" },
  "diff.normal": { en: "Normal", it: "Normale" },
  "diff.hard": { en: "Hard", it: "Difficile" },
  "diff.expert": { en: "Expert", it: "Esperto" },

  "region.local": { en: "Local Lattice", it: "Reticolo locale" },
  "region.north": { en: "North Relay", it: "Nodo Nord" },
  "region.central": { en: "Central Relay", it: "Nodo Centrale" },
  "region.south": { en: "South Relay", it: "Nodo Sud" },
  "region.island": { en: "Island Relay", it: "Nodo Insulare" },

  "mode.team_fracture.name": { en: "Team Fracture", it: "Frattura a squadre" },
  "mode.team_fracture.desc": { en: "Two teams race for eliminations. First to the limit, or the clock.", it: "Due squadre corrono alle eliminazioni. Vince chi arriva al limite, o allo scadere." },
  "mode.team_fracture.how": { en: "Team battle on a shared map. Every elimination scores a point — first squad to 100 wins, or the leader when the 7 minutes run out. Kills bring teammates back in ~3 seconds, so holding lanes and rotating between objectives beats hunting a single player.", it: "Scontro a squadre su una mappa condivisa. Ogni eliminazione vale un punto: vince la prima squadra a 100, o chi comanda allo scadere dei 7 minuti. I morti tornano in ~3 secondi, quindi tenere le corsie e ruotare tra gli obiettivi batte la caccia a un singolo." },
  "mode.free_fracture.name": { en: "Free Fracture", it: "Frattura libera" },
  "mode.free_fracture.desc": { en: "Everyone is a target. Highest eliminations when the circuit closes.", it: "Tutti sono bersagli. Contano le eliminazioni allo scadere." },
  "mode.free_fracture.how": { en: "Everyone for themselves. The match ends at 30 eliminations or when the 6-minute clock closes, and the player on top takes it. No teammates watch your back, so pick fights you can finish and use the flanks to set up ambushes.", it: "Ognuno per sé. La partita si chiude a 30 eliminazioni o allo scadere dei 6 minuti, e vince chi è in cima. Nessuno ti copre le spalle: scegli scontri che puoi chiudere e usa i fianchi per l'imboscata." },
  "mode.dominion.name": { en: "Dominion", it: "Dominio" },
  "mode.dominion.desc": { en: "Three zones. Hold them to bleed points onto the board.", it: "Tre zone. Tienile per far salire il punteggio." },
  "mode.dominion.how": { en: "Three scoring zones. Stand inside one to fill its capture bar; once your team owns it, every uncontested second bleeds points onto the board toward 250. A contested zone pauses progress — rotate to the point your team is losing.", it: "Tre zone di punteggio. Restaci dentro per riempirne la barra di cattura; quando la tua squadra la possiede, ogni secondo non contestato fa salire il punteggio verso 250. Una zona contestata mette in pausa i progressi — ruota sul punto che state perdendo." },
  "mode.pulsepoint.name": { en: "Pulsepoint", it: "Punto impulso" },
  "mode.pulsepoint.desc": { en: "One zone, always moving. Stand on it or lose the minute.", it: "Una zona, sempre in movimento. Presidiala o perdi il minuto." },
  "mode.pulsepoint.how": { en: "A single objective that never stays put. The active point swaps to a new location every 30 seconds, and the team standing on it scores over time toward 250. Watch the rotation — the point under your feet can go dark mid-fight, and the next one starts somewhere else.", it: "Un unico obiettivo che non resta mai fermo. Il punto attivo cambia posizione ogni 30 secondi, e la squadra che ci sta segna nel tempo verso 250. Occhio alla rotazione: il punto sotto i tuoi piedi può spegnersi a metà dello scontro, e il prossimo parte altrove." },
  "mode.core_run.name": { en: "Core Run", it: "Corsa al nucleo" },
  "mode.core_run.desc": { en: "Steal the enemy core and bring it home. Drop it if you fall.", it: "Ruba il nucleo nemico e riportalo a casa. Se cadi, lo lasci." },
  "mode.core_run.how": { en: "Each team's core sits near its own spawn. A player picks up the enemy core and carries it back to their own base to score — first team to 3 wins. Dying drops the core, and a carrier is a huge target, so the escort is the real fight.", it: "Il nucleo di ogni squadra sta vicino al suo spawn. Un giocatore raccoglie il nucleo nemico e lo riporta alla propria base per segnare — vince la prima squadra a 3. Se muori lo lasci a terra, e chi lo trasporta è un bersaglio enorme: la scorta è lo scontro vero." },
  "mode.last_circuit.name": { en: "Last Circuit", it: "Ultimo circuito" },
  "mode.last_circuit.desc": { en: "One life per round. Wipe the other side.", it: "Una vita a round. Svuota il lato opposto." },
  "mode.last_circuit.how": { en: "Round-based elimination. Each round gives both sides a single life and 80 seconds — no respawn, no regeneration. Wipe the enemy team to take the round (if the clock expires, the healthier team does); first team to 6 rounds wins the match.", it: "Eliminazione a round. Ogni round dà a entrambi i lati una sola vita e 80 secondi — niente respawn, niente rigenerazione. Svuota la squadra nemica per prendere il round (se scade il tempo, lo prende chi ha più salute); vince la prima squadra a 6 round." },
  "mode.arsenal_march.name": { en: "Arsenal March", it: "Marcia dell'arsenale" },
  "mode.arsenal_march.desc": { en: "Each elimination advances the weapon. Finish on the blade.", it: "Ogni eliminazione cambia arma. Si chiude con la lama." },
  "mode.arsenal_march.how": { en: "An everyone-for-themselves weapon ladder. An elimination steps your weapon up the 16-rung ladder; a death drops you back down. First to 16 eliminations — or the leader at 8:00 — wins, and the top rung is a blade, so the endgame is knives out.", it: "Una scala di armi, ognuno per sé. Un'eliminazione fa salire la tua arma di un gradino nella scala di 16; una morte ti fa scendere. Vince chi arriva a 16 eliminazioni — o chi comanda a 8:00 — e l'ultimo gradino è una lama, quindi si chiude a coltello." },
  "mode.ranked_circuit.name": { en: "Ranked Circuit", it: "Circuito classificato" },
  "mode.ranked_circuit.desc": { en: "No regeneration. Rating moves with the result, not the highlight reel.", it: "Niente rigenerazione. Il rating segue il risultato, non la clip." },
  "mode.ranked_circuit.how": { en: "The competitive circuit: team battle to 75 with no health regeneration — spent health stays spent until you respawn. Your loadout locks when the match starts, and on the relay the result moves your official rating, win or lose.", it: "Il circuito competitivo: scontro a squadre fino a 75 senza rigenerazione — la salute spesa resta spesa fino al respawn. L'equipaggiamento si blocca all'avvio della partita, e sul relay il risultato muove il tuo rating ufficiale, che tu vinca o perda." },
  "mode.practice.name": { en: "Calibration Bay", it: "Baia di calibrazione" },
  "mode.practice.desc": { en: "Still targets, a moving track, and every weapon on a pad.", it: "Bersagli fermi, un binario mobile e ogni arma su un piedistallo." },
  "mode.tutorial.name": { en: "First deployment", it: "Primo schieramento" },
  "mode.tutorial.desc": { en: "Movement, aim, abilities, and an objective. Under ten minutes.", it: "Movimento, mira, abilità e un obiettivo. Meno di dieci minuti." },

  "map.neon_district.name": { en: "Neon District", it: "Distretto Neon" },
  "map.neon_district.desc": { en: "Alleys, a raised yard, and a street that punishes hesitation.", it: "Vicoli, un piazzale rialzato e una strada che punisce chi esita." },
  "map.orbital_yard.name": { en: "Orbital Yard", it: "Cantiere orbitale" },
  "map.orbital_yard.desc": { en: "Container lanes and a cargo lift that changes the angle.", it: "Corsie di container e un montacarichi che cambia l'angolo." },
  "map.floodline.name": { en: "Floodline", it: "Linea di piena" },
  "map.floodline.desc": { en: "A slow channel, bridges, and doors that refuse to stay shut.", it: "Un canale lento, ponti e porte che non restano chiuse." },
  "map.dust_station.name": { en: "Dust Station", it: "Stazione polvere" },
  "map.dust_station.desc": { en: "Train cars, an open yard, and a maintenance trench.", it: "Vagoni, un cortile aperto e una trincea di manutenzione." },
  "map.skybridge.name": { en: "Skybridge", it: "Ponte cielo" },
  "map.skybridge.desc": { en: "Two towers, glass you can break, and fights on three heights.", it: "Due torri, vetri che si spezzano e scontri su tre altezze." },
  "map.glassworks.name": { en: "Glassworks", it: "Vetreria" },
  "map.glassworks.desc": { en: "Long machine lanes and a loft over the south gate.", it: "Lunghe corsie di macchinari e un soppalco sul varco sud." },
  "map.relay_spire.name": { en: "Relay Spire", it: "Guglia relay" },
  "map.relay_spire.desc": { en: "A ring around a core column. Rotate or get cut.", it: "Un anello attorno a una colonna. Ruota o vieni tagliato." },
  "map.cinder_market.name": { en: "Cinder Market", it: "Mercato brace" },
  "map.cinder_market.desc": { en: "Stalls, short sights, and a plaza that belongs to whoever moves.", it: "Banchi, linee corte e una piazza di chi si muove." },
  "map.sublevel_9.name": { en: "Sublevel 9", it: "Sottolivello 9" },
  "map.sublevel_9.desc": { en: "Pillars, a parked consist, and no long apologies.", it: "Pilastri, un convoglio fermo e niente scuse lunghe." },
  "map.harbor_lattice.name": { en: "Harbor Lattice", it: "Reticolo porto" },
  "map.harbor_lattice.desc": { en: "Docks, a hull you can climb, and water that ends the run.", it: "Banchine, uno scafo da scalare e acqua che chiude la corsa." },
  "map.atrium_loop.name": { en: "Atrium Loop", it: "Anello atrio" },
  "map.atrium_loop.desc": { en: "A pit, a gallery, and three ways to cross.", it: "Una fossa, una galleria e tre modi per attraversare." },
  "map.calibration_bay.name": { en: "Calibration Bay", it: "Baia di calibrazione" },
  "map.calibration_bay.desc": { en: "A measured range. Learn the kick before the circuit does.", it: "Un poligono misurato. Impara il calcio prima del circuito." },

  "cat.ar": { en: "Assault rifles", it: "Fucili d'assalto" },
  "cat.smg": { en: "SMGs", it: "Mitragliette" },
  "cat.shotgun": { en: "Shotguns", it: "Fucili a canna liscia" },
  "cat.sniper": { en: "Snipers", it: "Cecchini" },
  "cat.marksman": { en: "Marksman", it: "Tiratori" },
  "cat.lmg": { en: "LMGs", it: "Mitragliatrici" },
  "cat.pistol": { en: "Pistols", it: "Pistole" },
  "cat.experimental": { en: "Experimental", it: "Sperimentali" },
  "cat.melee": { en: "Melee", it: "Mischia" },

  "weapon.linecut.name": { en: "Linecut", it: "Tagliolinea" },
  "weapon.linecut.desc": { en: "Balanced rifle. The pattern climbs, then walks right.", it: "Fucile equilibrato. Lo schema sale, poi cammina a destra." },
  "weapon.ashford.name": { en: "Ashford-4", it: "Ashford-4" },
  "weapon.ashford.desc": { en: "Hard-hitting rifle. Misses are expensive.", it: "Fucile pesante. Gli errori costano." },
  "weapon.cinderline.name": { en: "Cinderline", it: "Linea brace" },
  "weapon.cinderline.desc": { en: "Fast rifle that falls apart past the alley.", it: "Fucile rapido che si spegne oltre il vicolo." },
  "weapon.bastionk.name": { en: "Bastion-K", it: "Bastione K" },
  "weapon.bastionk.desc": { en: "Stable lane rifle. Slow to shoulder, calm once there.", it: "Fucile da corsia, stabile. Lento da imbracciare, poi calmo." },
  "weapon.kestrel.name": { en: "Kestrel-9", it: "Gheppio-9" },
  "weapon.kestrel.desc": { en: "Close rifle-fast SMG. Do not duel the long street.", it: "Mitraglietta rapida da vicino. Non duellare sulla strada lunga." },
  "weapon.ripcord.name": { en: "Ripcord", it: "Strappo" },
  "weapon.ripcord.desc": { en: "A hose. Wins inside a room, loses the doorway.", it: "Un tubo. Vince nella stanza, perde sulla soglia." },
  "weapon.velvet.name": { en: "Velvet-3", it: "Velluto-3" },
  "weapon.velvet.desc": { en: "The accurate SMG. Burst it like you mean the head.", it: "La mitraglietta precisa. Spara a raffiche se punti la testa." },
  "weapon.needleburst.name": { en: "Needleburst", it: "Raffica d'ago" },
  "weapon.needleburst.desc": { en: "Three tight needles. Reset if the first one misses.", it: "Tre aghi stretti. Resetta se il primo manca." },
  "weapon.hammerfall.name": { en: "Hammerfall", it: "Martelcaduta" },
  "weapon.hammerfall.desc": { en: "Pump shotgun. All pellets, or none of the fight.", it: "A pompa. Tutti i pallini, o niente scontro." },
  "weapon.scatterwake.name": { en: "Scatterwake", it: "Scia sparsa" },
  "weapon.scatterwake.desc": { en: "Semi-auto scatter. Wider, faster, hungrier for reloads.", it: "Semiautomatico largo. Più veloce, più affamato di ricariche." },
  "weapon.breachjaw.name": { en: "Breachjaw", it: "Mascella" },
  "weapon.breachjaw.desc": { en: "A slug. Aim it or donate the round.", it: "Una palla unica. Mirala o regalala." },
  "weapon.glassline.name": { en: "Glassline", it: "Linea di vetro" },
  "weapon.glassline.desc": { en: "Bolt rifle. A head ends it. A body asks for a second.", it: "A otturatore. La testa chiude. Il corpo ne chiede un'altra." },
  "weapon.quietmeridian.name": { en: "Quiet Meridian", it: "Meridiano quieto" },
  "weapon.quietmeridian.desc": { en: "Softer report, faster cycle. Still a sniper's promise.", it: "Colpo più morbido, ciclo più rapido. Resta una promessa da cecchino." },
  "weapon.longbow.name": { en: "Longbow-M", it: "Arco lungo" },
  "weapon.longbow.desc": { en: "Marksman rifle. Two calm shots beat one panicked spray.", it: "Tiratore. Due colpi calmi battono una raffica in panico." },
  "weapon.arcstitch.name": { en: "Arcstitch", it: "Cucitura d'arco" },
  "weapon.arcstitch.desc": { en: "Energy pair. The second stitch is the one that counts.", it: "Coppia energetica. Il secondo punto è quello che conta." },
  "weapon.furnace.name": { en: "Furnace", it: "Fornace" },
  "weapon.furnace.desc": { en: "Long belt, short legs. Hold a door, do not chase one.", it: "Nastro lungo, gambe corte. Tieni una porta, non inseguirla." },
  "weapon.drumline.name": { en: "Drumline-80", it: "Rullante-80" },
  "weapon.drumline.desc": { en: "The mobile drum. Still not a rifle.", it: "Il tamburo mobile. Non è comunque un fucile." },
  "weapon.anchor.name": { en: "Anchor", it: "Ancora" },
  "weapon.anchor.desc": { en: "Low kick, low speed. Plant and make them come to you.", it: "Poco rinculo, poca velocità. Pianta e falli venire." },
  "weapon.flick2.name": { en: "Flick-2", it: "Scatto-2" },
  "weapon.flick2.desc": { en: "Sidearm that leaves the holster already aimed.", it: "Secondaria che esce dalla fondina già mirata." },
  "weapon.ironpetal.name": { en: "Ironpetal", it: "Petalo di ferro" },
  "weapon.ironpetal.desc": { en: "Slow pistol, heavy petal. Make the first one land.", it: "Pistola lenta, petalo pesante. Fai arrivare il primo." },
  "weapon.sparkside.name": { en: "Sparkside", it: "Lato scintilla" },
  "weapon.sparkside.desc": { en: "Three-round pocket burst. A backup, not a career.", it: "Raffica da tasca. Un piano B, non una carriera." },
  "weapon.helix.name": { en: "Helix", it: "Elica" },
  "weapon.helix.desc": { en: "Four-round energy burst. Hipfire is a rumor.", it: "Raffica energetica da quattro. Il fuoco in movimento è una voce." },
  "weapon.pulse7.name": { en: "Pulse-7", it: "Impulso-7" },
  "weapon.pulse7.desc": { en: "A short energy fan. Past ten meters it is a flashlight.", it: "Un ventaglio energetico corto. Oltre dieci metri è una torcia." },
  "weapon.bankshot.name": { en: "Bankshot", it: "Rimpallo" },
  "weapon.bankshot.desc": { en: "One bounce. The corner is not cover if you can read it.", it: "Un rimbalzo. L'angolo non è copertura se sai leggerlo." },
  "weapon.overcast.name": { en: "Overcast", it: "Coperto" },
  "weapon.overcast.desc": { en: "Charge it. You are slow while the sky gathers.", it: "Caricala. Sei lento mentre il cielo si addensa." },
  "weapon.orbitlance.name": { en: "Orbit Lance", it: "Lancia orbitale" },
  "weapon.orbitlance.desc": { en: "A piercing dart. Line two people up and keep the receipt.", it: "Un dardo perforante. Allinea due persone e tieni lo scontrino." },
  "weapon.echosplitter.name": { en: "Echo Splitter", it: "Eco diviso" },
  "weapon.echosplitter.desc": { en: "One shot that splits after ten meters. Learn the seam.", it: "Un colpo che si divide dopo dieci metri. Impara la cucitura." },
  "weapon.gravneedle.name": { en: "Grav Needle", it: "Ago grav" },
  "weapon.gravneedle.desc": { en: "Slow, heavy, dodgeable. A hit drags their feet.", it: "Lento, pesante, schivabile. Un colpo gli frena i piedi." },
  "weapon.vectorblade.name": { en: "Vector Blade", it: "Lama vettore" },
  "weapon.vectorblade.desc": { en: "A quick cut. Not a plan, a punctuation mark.", it: "Un taglio rapido. Non è un piano, è un punto." },
  "weapon.shockknuckle.name": { en: "Shock Knuckle", it: "Nocche shock" },
  "weapon.shockknuckle.desc": { en: "Short, mean, and a little slower than pride.", it: "Corto, cattivo e un po' più lento dell'orgoglio." },

  "attach.heavy_barrel": { en: "Heavy barrel", it: "Canna pesante" },
  "attach.heavy_barrel.desc": { en: "More range. Slower reload.", it: "Più gittata. Ricarica più lenta." },
  "attach.light_barrel": { en: "Light barrel", it: "Canna leggera" },
  "attach.light_barrel.desc": { en: "More mobility. More recoil.", it: "Più mobilità. Più rinculo." },
  "attach.reflex": { en: "Reflex glass", it: "Vetro reflex" },
  "attach.reflex.desc": { en: "Faster aim. Less zoom.", it: "Mira più rapida. Meno zoom." },
  "attach.scout_optic": { en: "Scout optic", it: "Ottica scout" },
  "attach.scout_optic.desc": { en: "More zoom. Slower aim.", it: "Più zoom. Mira più lenta." },
  "attach.extended_mag": { en: "Extended cell", it: "Cella estesa" },
  "attach.extended_mag.desc": { en: "More rounds. Slower reload.", it: "Più colpi. Ricarica più lenta." },
  "attach.quick_mag": { en: "Quick cell", it: "Cella rapida" },
  "attach.quick_mag.desc": { en: "Faster reload. Fewer rounds.", it: "Ricarica più rapida. Meno colpi." },
  "attach.light_stock": { en: "Light stock", it: "Calcio leggero" },
  "attach.light_stock.desc": { en: "More mobility. More recoil.", it: "Più mobilità. Più rinculo." },
  "attach.stable_stock": { en: "Stable stock", it: "Calcio stabile" },
  "attach.stable_stock.desc": { en: "Less recoil. Less mobility.", it: "Meno rinculo. Meno mobilità." },
  "attach.locked": { en: "Earn weapon level {n} to unlock this slot.", it: "Raggiungi il livello arma {n} per sbloccare questo slot." },
  "attach.none": { en: "None", it: "Nessuno" },

  "role.runner": { en: "Runner", it: "Corridore" },
  "role.vanguard": { en: "Vanguard", it: "Avanguardia" },
  "role.scout": { en: "Scout", it: "Esploratore" },
  "role.engineer": { en: "Engineer", it: "Ingegnere" },
  "role.striker": { en: "Striker", it: "Attaccante" },
  "role.sentinel": { en: "Sentinel", it: "Sentinella" },
  "role.ghost": { en: "Ghost", it: "Fantasma" },
  "role.technician": { en: "Technician", it: "Tecnico" },
  "role.bruiser": { en: "Bruiser", it: "Sfondatore" },
  "role.vertical": { en: "Vertical", it: "Verticale" },
  "role.support": { en: "Support", it: "Supporto" },
  "role.experimental": { en: "Oddment", it: "Anomalia" },

  "op.ryn.name": { en: "Ryn Slip", it: "Ryn Slip" },
  "op.ryn.blurb": { en: "Arrives early and leaves a draft.", it: "Arriva prima e lascia una corrente." },
  "op.ryn.passive": { en: "Passive: quicker feet, longer drifts.", it: "Passiva: piedi più rapidi, scivolate più lunghe." },
  "op.ryn.tactical": { en: "Overdrive: a short speed burst.", it: "Overdrive: un breve scatto di velocità." },
  "op.ryn.ultimate": { en: "Vector Line: six seconds of unfair pace. Still mortal.", it: "Linea vettore: sei secondi di passo ingiusto. Sempre mortale." },
  "op.kael.name": { en: "Kael Voss", it: "Kael Voss" },
  "op.kael.blurb": { en: "Stands where the lane narrows.", it: "Sta dove la corsia si stringe." },
  "op.kael.passive": { en: "Passive: a little extra armor on spawn.", it: "Passiva: un po' di armatura in più allo spawn." },
  "op.kael.tactical": { en: "Aegis Plate: a waist-high wall.", it: "Piastra egida: un muro all'altezza della vita." },
  "op.kael.ultimate": { en: "Iron Hymn: temporary armor and a dent of resistance.", it: "Inno di ferro: armatura temporanea e un filo di resistenza." },
  "op.lumen.name": { en: "Lumen Park", it: "Lumen Park" },
  "op.lumen.blurb": { en: "Sees the fight one second sooner.", it: "Vede lo scontro un secondo prima." },
  "op.lumen.passive": { en: "Passive: people you hit stay marked briefly.", it: "Passiva: chi colpisci resta segnato per un attimo." },
  "op.lumen.tactical": { en: "Ping Sweep: reveal nearby hostiles.", it: "Spazzata: rivela i nemici vicini." },
  "op.lumen.ultimate": { en: "Lattice Eye: the whole team sees them. Briefly.", it: "Occhio del reticolo: tutta la squadra li vede. Per poco." },
  "op.brassa.name": { en: "Brassa Holt", it: "Brassa Holt" },
  "op.brassa.blurb": { en: "Leaves tools where the angle is bad.", it: "Lascia attrezzi dove l'angolo è cattivo." },
  "op.brassa.passive": { en: "Passive: faster reloads beside your own gear.", it: "Passiva: ricariche più rapide vicino ai tuoi dispositivi." },
  "op.brassa.tactical": { en: "Sentry Pylon: a slow, honest turret.", it: "Pilone sentinella: una torretta lenta e onesta." },
  "op.brassa.ultimate": { en: "Fortify: a long wall with a health bar.", it: "Fortifica: un muro lungo con una barra di salute." },
  "op.sable.name": { en: "Sable Rift", it: "Sable Rift" },
  "op.sable.blurb": { en: "Closes distance like it insulted them.", it: "Chiude la distanza come se l'avesse insultata." },
  "op.sable.passive": { en: "Passive: a short damage bump after a dodge.", it: "Passiva: un breve bonus danni dopo una schivata." },
  "op.sable.tactical": { en: "Blink Step: a short teleport along your aim.", it: "Passo blink: un teletrasporto corto lungo la mira." },
  "op.sable.ultimate": { en: "Shatter Charge: a lobbed blast. Do not hug it.", it: "Carica frattura: un'esplosione lanciata. Non abbracciarla." },
  "op.orrin.name": { en: "Orrin Hold", it: "Orrin Hold" },
  "op.orrin.blurb": { en: "Makes a doorway feel like a mistake.", it: "Fa sembrare una porta un errore." },
  "op.orrin.passive": { en: "Passive: less flinch when tagged.", it: "Passiva: meno sussulto quando ti colpiscono." },
  "op.orrin.tactical": { en: "Snare Disc: a pool that steals speed.", it: "Disco laccio: una pozza che ruba velocità." },
  "op.orrin.ultimate": { en: "Bastion Dome: a shell. Shoot around it or wait.", it: "Cupola bastione: un guscio. Giraci intorno o aspetta." },
  "op.nyx.name": { en: "Nyx Vale", it: "Nyx Vale" },
  "op.nyx.blurb": { en: "Footsteps like a rumor.", it: "Passi come una voce." },
  "op.nyx.passive": { en: "Passive: quieter steps.", it: "Passiva: passi più silenziosi." },
  "op.nyx.tactical": { en: "Shade Screen: smoke that blinds scans.", it: "Schermo d'ombra: fumo che acceca le scansioni." },
  "op.nyx.ultimate": { en: "Mirror Decoy: two runners that are not you.", it: "Decoy specchio: due corridori che non sei tu." },
  "op.tess.name": { en: "Tess Quill", it: "Tess Quill" },
  "op.tess.blurb": { en: "Talks to machines more than people.", it: "Parla alle macchine più che alle persone." },
  "op.tess.passive": { en: "Passive: abilities return a little sooner.", it: "Passiva: le abilità tornano un po' prima." },
  "op.tess.tactical": { en: "Hex Drone: a pet that spots and nips.", it: "Drone hex: un animale che segna e pizzica." },
  "op.tess.ultimate": { en: "Blackout: locks enemy abilities in a radius.", it: "Blackout: blocca le abilità nemiche in un raggio." },
  "op.marrow.name": { en: "Marrow Dunn", it: "Marrow Dunn" },
  "op.marrow.blurb": { en: "Extra bone, same trigger.", it: "Più osso, stesso grilletto." },
  "op.marrow.passive": { en: "Passive: a thicker health pool.", it: "Passiva: più salute." },
  "op.marrow.tactical": { en: "Ground Slam: leap, then a landing shock.", it: "Schianto: salto, poi un urto all'atterraggio." },
  "op.marrow.ultimate": { en: "Unbreakable: meaner melee, a little harder to drop.", it: "Indistruttibile: mischia più cattiva, un po' più duro da buttare giù." },
  "op.ione.name": { en: "Ione Spire", it: "Ione Spire" },
  "op.ione.blurb": { en: "Treats roofs as hallways.", it: "Tratta i tetti come corridoi." },
  "op.ione.passive": { en: "Passive: higher jump, quicker vaults.", it: "Passiva: salto più alto, scavalcamenti più rapidi." },
  "op.ione.tactical": { en: "Updraft: a vertical kick.", it: "Corrente: un calcio verticale." },
  "op.ione.ultimate": { en: "Skyhook: lighter gravity, higher leaps.", it: "Gancio cielo: gravità più leggera, salti più alti." },
  "op.peck.name": { en: "Peck Solis", it: "Peck Solis" },
  "op.peck.blurb": { en: "Keeps the line from fraying.", it: "Impedisce alla linea di sfilacciarsi." },
  "op.peck.passive": { en: "Passive: regeneration starts sooner.", it: "Passiva: la rigenerazione parte prima." },
  "op.peck.tactical": { en: "Mend Field: a small healing pool.", it: "Campo rammendo: una piccola pozza di cura." },
  "op.peck.ultimate": { en: "Triage Burst: a snap heal for nearby allies.", it: "Triage: una cura istantanea per gli alleati vicini." },
  "op.vesper.name": { en: "Vesper Odd", it: "Vesper Odd" },
  "op.vesper.blurb": { en: "Carries weapons that should not exist yet.", it: "Porta armi che non dovrebbero ancora esistere." },
  "op.vesper.passive": { en: "Passive: experimental darts fly a little faster.", it: "Passiva: i dardi sperimentali volano un po' più veloci." },
  "op.vesper.tactical": { en: "Phase Pocket: a blink of intangibility. You cannot shoot.", it: "Tasca di fase: un attimo intangibile. Non puoi sparare." },
  "op.vesper.ultimate": { en: "Catalog: experimental weapons cycle faster for a few seconds.", it: "Catalogo: le armi sperimentali ciclano più in fretta per qualche secondo." },

  "hud.health": { en: "Health", it: "Salute" },
  "hud.armor": { en: "Armor", it: "Armatura" },
  "hud.ammo": { en: "Ammo", it: "Munizioni" },
  "hud.reload": { en: "Reloading", it: "Ricarica" },
  "hud.tactical": { en: "Tactic", it: "Tattica" },
  "hud.ultimate": { en: "Ultimate", it: "Ultra" },
  "hud.ready": { en: "Ready", it: "Pronto" },
  "hud.active": { en: "Active", it: "Attiva" },
  "hud.elim": { en: "Eliminations", it: "Eliminazioni" },
  "hud.personal": { en: "Personal", it: "Personali" },
  "hud.score": { en: "Score", it: "Punteggio" },
  "hud.objective": { en: "Objective", it: "Obiettivo" },
  "hud.contested": { en: "Contested", it: "Conteso" },
  "hud.neutral": { en: "Neutral", it: "Neutro" },
  "hud.held": { en: "Held", it: "Presidiato" },
  "hud.respawn": { en: "Respawn", it: "Rientro" },
  "hud.down": { en: "Operator down", it: "Operatore a terra" },
  "hud.killed_by": { en: "Fractured by", it: "Fratturato da" },
  "hud.change_kit": { en: "Change kit", it: "Cambia kit" },
  "hud.overtime": { en: "Overtime", it: "Supplementari" },
  "hud.round": { en: "Round", it: "Round" },
  "hud.spectate": { en: "Spectating", it: "Osservazione" },
  "hud.freecam": { en: "Free camera", it: "Camera libera" },
  "hud.ping": { en: "Ping", it: "Ping" },
  "hud.loss": { en: "Loss", it: "Perdita" },
  "hud.fps": { en: "FPS", it: "FPS" },
  "hud.region": { en: "Relay", it: "Nodo" },
  "hud.charge": { en: "Charge", it: "Carica" },
  "hud.core": { en: "Core", it: "Nucleo" },
  "hud.carry": { en: "Carrying core", it: "Nucleo in mano" },
  "hud.interact": { en: "Interact", it: "Interagisci" },
  "hud.wave": { en: "Tier", it: "Grado" },
  "hud.headshot": { en: "HS", it: "TC" },
  "hud.reserve": { en: "Reserve", it: "Riserva" },
  "hud.you": { en: "You", it: "Tu" },

  "score.elim": { en: "Elimination +100", it: "Eliminazione +100" },
  "score.assist": { en: "Assist +50", it: "Assist +50" },
  "score.capture": { en: "Capture +150", it: "Cattura +150" },
  "score.defend": { en: "Objective defense +75", it: "Difesa obiettivo +75" },
  "score.obj": { en: "Objective elimination +125", it: "Eliminazione sull'obiettivo +125" },
  "score.support": { en: "Team support +50", it: "Supporto squadra +50" },
  "score.core": { en: "Core return +200", it: "Rientro nucleo +200" },
  "score.legend": { en: "Scoring", it: "Punteggio" },
  "score.kills": { en: "K", it: "U" },
  "score.deaths": { en: "D", it: "M" },
  "score.assists": { en: "A", it: "A" },
  "score.objshort": { en: "OBJ", it: "OBI" },
  "score.ping": { en: "Ping", it: "Ping" },
  "score.you": { en: "You", it: "Tu" },
  "score.drill": { en: "Drill", it: "Drill" },
  "score.team_a": { en: "Cyan", it: "Ciano" },
  "score.team_b": { en: "Ember", it: "Brace" },
  "score.draw": { en: "Draw", it: "Pareggio" },
  "score.victory": { en: "Circuit closed", it: "Circuito chiuso" },
  "score.defeat": { en: "Line broken", it: "Linea spezzata" },
  "score.mvp": { en: "Signal", it: "Segnale" },
  "score.xp": { en: "XP", it: "XP" },
  "score.credits": { en: "Credits", it: "Crediti" },
  "score.level": { en: "Level", it: "Livello" },
  "score.report": { en: "Report", it: "Segnala" },
  "score.commend": { en: "Commend", it: "Elogia" },
  "score.mute": { en: "Mute", it: "Silenzia" },
  "score.block": { en: "Block", it: "Blocca" },

  "announce.go": { en: "Break.", it: "Spezza." },
  "announce.overtime": { en: "Overtime. Next point closes it.", it: "Supplementari. Il prossimo punto chiude." },
  "announce.captured": { en: "Zone seized.", it: "Zona presa." },
  "announce.rotate": { en: "Pulsepoint moved.", it: "Il punto impulso si è spostato." },
  "announce.core_taken": { en: "Core taken.", it: "Nucleo preso." },
  "announce.core_home": { en: "Core home.", it: "Nucleo a casa." },
  "announce.core_recovered": { en: "Core recovered.", it: "Nucleo recuperato." },
  "announce.core_dropped": { en: "Core dropped.", it: "Nucleo lasciato." },
  "announce.round": { en: "Round closed.", it: "Round chiuso." },
  "announce.circuit_closed": { en: "Circuit closed.", it: "Circuito chiuso." },
  "announce.level": { en: "Level up.", it: "Livello aumentato." },
  "announce.achievement": { en: "Badge etched.", it: "Distintivo inciso." },

  "set.graphics": { en: "Graphics", it: "Grafica" },
  "set.controls": { en: "Controls", it: "Controlli" },
  "set.audio": { en: "Audio", it: "Audio" },
  "set.gameplay": { en: "Gameplay", it: "Gioco" },
  "set.accessibility": { en: "Accessibility", it: "Accessibilità" },
  "set.preset": { en: "Preset", it: "Predefinito" },
  "set.low": { en: "Low", it: "Bassa" },
  "set.medium": { en: "Medium", it: "Media" },
  "set.high": { en: "High", it: "Alta" },
  "set.ultra": { en: "Ultra", it: "Ultra" },
  "set.fov": { en: "Field of view", it: "Campo visivo" },
  "set.shadows": { en: "Shadows", it: "Ombre" },
  "set.particles": { en: "Particles", it: "Particelle" },
  "set.aa": { en: "Anti-aliasing", it: "Antialiasing" },
  "set.fpscap": { en: "Frame limit", it: "Limite fotogrammi" },
  "set.vsync": { en: "VSync hint", it: "Suggerimento VSync" },
  "set.sens": { en: "Mouse sensitivity", it: "Sensibilità mouse" },
  "set.sensx": { en: "X sensitivity", it: "Sensibilità X" },
  "set.sensy": { en: "Y sensitivity", it: "Sensibilità Y" },
  "set.ads": { en: "Aim sensitivity", it: "Sensibilità mira" },
  "set.inverty": { en: "Invert Y", it: "Inverti Y" },
  "set.bind": { en: "Key bindings", it: "Tasti" },
  "set.press": { en: "Press a key…", it: "Premi un tasto…" },
  "set.master": { en: "Master", it: "Generale" },
  "set.music": { en: "Music", it: "Musica" },
  "set.sfx": { en: "Effects", it: "Effetti" },
  "set.voice": { en: "Voice", it: "Voce" },
  "set.damage_numbers": { en: "Damage numbers", it: "Numeri danno" },
  "set.hitmarkers": { en: "Hit markers", it: "Segnali di colpo" },
  "set.killfeed": { en: "Kill feed", it: "Registro eliminazioni" },
  "set.subtitles": { en: "Subtitles", it: "Sottotitoli" },
  "set.shake": { en: "Camera shake", it: "Scossa camera" },
  "set.reduce_shake": { en: "Reduce camera shake", it: "Riduci scossa camera" },
  "set.reduce_fx": { en: "Reduce visual effects", it: "Riduci effetti visivi" },
  "set.ui_scale": { en: "UI scale", it: "Scala interfaccia" },
  "set.colorblind": { en: "Colorblind mode", it: "Modalità daltonismo" },
  "set.cb.off": { en: "Off", it: "Disattiva" },
  "set.cb.deutan": { en: "Deuteranopia", it: "Deuteranopia" },
  "set.cb.protan": { en: "Protanopia", it: "Protanopia" },
  "set.cb.tritan": { en: "Tritanopia", it: "Tritanopia" },
  "set.crosshair": { en: "Crosshair", it: "Mirino" },
  "set.ch.size": { en: "Size", it: "Dimensione" },
  "set.ch.thick": { en: "Thickness", it: "Spessore" },
  "set.ch.gap": { en: "Gap", it: "Apertura" },
  "set.ch.opacity": { en: "Opacity", it: "Opacità" },
  "set.ch.dynamic": { en: "Dynamic", it: "Dinamico" },
  "set.ch.dot": { en: "Center dot", it: "Punto centrale" },
  "set.ch.style": { en: "Style", it: "Stile" },
  "set.controller": { en: "Controller", it: "Controller" },
  "set.deadzone": { en: "Dead zone", it: "Zona morta" },
  "set.aimassist": { en: "Aim assist", it: "Assistenza mira" },
  "set.vibration": { en: "Vibration", it: "Vibrazione" },
  "set.accel": { en: "Look acceleration", it: "Accelerazione visuale" },
  "set.minimap": { en: "Minimap", it: "Minimappa" },
  "set.showfps": { en: "Show FPS", it: "Mostra FPS" },
  "set.shoulder": { en: "Default shoulder", it: "Spalla predefinita" },
  "set.left": { en: "Left", it: "Sinistra" },
  "set.right": { en: "Right", it: "Destra" },
  "set.unlimited": { en: "Unlimited", it: "Illimitato" },

  "bind.forward": { en: "Forward", it: "Avanti" },
  "bind.back": { en: "Back", it: "Indietro" },
  "bind.left": { en: "Left", it: "Sinistra" },
  "bind.right": { en: "Right", it: "Destra" },
  "bind.jump": { en: "Jump", it: "Salto" },
  "bind.crouch": { en: "Crouch / drift", it: "Accovacciati / scivola" },
  "bind.sprint": { en: "Sprint", it: "Scatto" },
  "bind.fire": { en: "Fire", it: "Fuoco" },
  "bind.aim": { en: "Aim", it: "Mira" },
  "bind.reload": { en: "Reload", it: "Ricarica" },
  "bind.melee": { en: "Melee", it: "Mischia" },
  "bind.tactical": { en: "Tactic", it: "Tattica" },
  "bind.ultimate": { en: "Ultimate", it: "Ultra" },
  "bind.dodge": { en: "Dodge", it: "Schivata" },
  "bind.interact": { en: "Interact", it: "Interagisci" },
  "bind.shoulder": { en: "Swap shoulder", it: "Cambia spalla" },
  "bind.slot1": { en: "Primary", it: "Primaria" },
  "bind.slot2": { en: "Secondary", it: "Secondaria" },
  "bind.slot3": { en: "Melee slot", it: "Slot mischia" },
  "bind.scoreboard": { en: "Scoreboard", it: "Tabellone" },
  "bind.pause": { en: "Pause", it: "Pausa" },
  "bind.chat": { en: "Quick chat", it: "Chat rapida" },
  "bind.drop": { en: "Drop core", it: "Lascia nucleo" },
  "bind.lookLeft": { en: "Look left", it: "Guarda a sinistra" },
  "bind.lookRight": { en: "Look right", it: "Guarda a destra" },
  "bind.lookUp": { en: "Look up", it: "Guarda su" },
  "bind.lookDown": { en: "Look down", it: "Guarda giù" },

  "chat.move": { en: "Moving in.", it: "Entro." },
  "chat.spotted": { en: "Enemy spotted.", it: "Nemico visto." },
  "chat.help": { en: "Need help.", it: "Serve aiuto." },
  "chat.cover": { en: "Cover me.", it: "Copritemi." },
  "chat.objective": { en: "On the objective.", it: "Sull'obiettivo." },
  "chat.nice": { en: "Clean.", it: "Pulito." },
  "chat.reloading": { en: "Reloading.", it: "Ricarico." },
  "chat.ult": { en: "Ultimate ready.", it: "Ultra pronta." },
  "chat.hold": { en: "Hold quick chat", it: "Tieni premuto per la chat rapida" },

  "profile.level": { en: "Level", it: "Livello" },
  "profile.kd": { en: "K/D", it: "U/M" },
  "profile.wins": { en: "Wins", it: "Vittorie" },
  "profile.matches": { en: "Matches", it: "Partite" },
  "profile.accuracy": { en: "Accuracy", it: "Precisione" },
  "profile.headshot": { en: "Headshot rate", it: "Percentuale teste" },
  "profile.playtime": { en: "Playtime", it: "Tempo di gioco" },
  "profile.favorite": { en: "Favorite weapon", it: "Arma preferita" },
  "profile.rating": { en: "Rating", it: "Rating" },
  "profile.name": { en: "Callsign", it: "Nominativo" },
  "profile.achievements": { en: "Badges", it: "Distintivi" },
  "profile.challenges": { en: "Challenges", it: "Sfide" },
  "profile.daily": { en: "Daily", it: "Giornaliere" },
  "profile.weekly": { en: "Weekly", it: "Settimanali" },
  "profile.export": { en: "Export profile", it: "Esporta profilo" },
  "profile.import": { en: "Import profile", it: "Importa profilo" },
  "profile.local": { en: "Stored on this device. Online matches credit the relay, not the browser.", it: "Salvato su questo dispositivo. Le partite online accreditano il nodo, non il browser." },
  "profile.none": { en: "No favorite yet.", it: "Nessuna preferita, per ora." },

  "rank.drift": { en: "Drift", it: "Deriva" },
  "rank.pulse": { en: "Pulse", it: "Impulso" },
  "rank.signal": { en: "Signal", it: "Segnale" },
  "rank.vector": { en: "Vector", it: "Vettore" },
  "rank.apex": { en: "Apex", it: "Apice" },
  "rank.crown": { en: "Crown", it: "Corona" },
  "rank.singularity": { en: "Singularity", it: "Singolarità" },
  "rank.placements": { en: "Placement circuits left: {n}", it: "Circuiti di piazzamento rimasti: {n}" },
  "rank.note": { en: "Winning the circuit matters more than the kill column.", it: "Vincere il circuito conta più della colonna uccisioni." },
  "rank.queue": { en: "Queue ranked", it: "Coda classificata" },
  "rank.abandon": { en: "Repeated ranked abandons delay your next queue. Server faults do not.", it: "Gli abbandoni ripetuti in classificata ritardano la coda. I guasti del server no." },
  "rank.locked": { en: "Queue locked for {n}s after repeated abandons.", it: "Coda bloccata per {n}s dopo abbandoni ripetuti." },
  "rank.local_warn": { en: "Drills do not move official rating. This is a local calibration.", it: "I Drill non muovono il rating ufficiale. È una calibrazione locale." },

  "lb.global": { en: "Global", it: "Globale" },
  "lb.regional": { en: "Regional", it: "Regionale" },
  "lb.weekly": { en: "Weekly", it: "Settimanale" },
  "lb.season": { en: "Season", it: "Stagione" },
  "lb.rating": { en: "Rating", it: "Rating" },
  "lb.wins": { en: "Wins", it: "Vittorie" },
  "lb.elims": { en: "Eliminations", it: "Eliminazioni" },
  "lb.obj": { en: "Objective score", it: "Punteggio obiettivi" },
  "lb.offline": { en: "Showing this device plus archived circuit records.", it: "Mostro questo dispositivo più archivi di circuito." },
  "lb.you": { en: "Your mark", it: "Il tuo segno" },

  "board.credits": { en: "Credits", it: "Crediti" },
  "board.buy": { en: "Exchange", it: "Scambia" },
  "board.owned": { en: "Owned", it: "Posseduto" },
  "board.equip": { en: "Equip", it: "Equipaggia" },
  "board.equipped": { en: "Equipped", it: "Equipaggiato" },
  "board.cosmetic": { en: "Cosmetics only. Nothing here changes damage, health, or speed.", it: "Solo estetica. Niente qui cambia danni, salute o velocità." },
  "board.skins": { en: "Operator finishes", it: "Finiture operatore" },
  "board.weapons": { en: "Weapon finishes", it: "Finiture arma" },
  "board.emotes": { en: "Emotes", it: "Emote" },
  "board.banners": { en: "Banners", it: "Stendardi" },
  "board.effects": { en: "Break effects", it: "Effetti frattura" },
  "board.cross": { en: "Crosshair styles", it: "Stili mirino" },

  "kit.primary": { en: "Primary", it: "Primaria" },
  "kit.secondary": { en: "Secondary", it: "Secondaria" },
  "kit.melee": { en: "Melee", it: "Mischia" },
  "kit.slot": { en: "Kit {n}", it: "Kit {n}" },
  "kit.rename": { en: "Kit name", it: "Nome kit" },
  "kit.operator": { en: "Operator", it: "Operatore" },
  "kit.ttk": { en: "Estimated body time", it: "Tempo stimato al corpo" },
  "kit.dps": { en: "Close DPS", it: "DPS ravvicinato" },
  "kit.range": { en: "Range", it: "Gittata" },
  "kit.mobility": { en: "Mobility", it: "Mobilità" },
  "kit.mag": { en: "Magazine", it: "Caricatore" },
  "kit.reload": { en: "Reload", it: "Ricarica" },
  "kit.fire": { en: "Cycle", it: "Ciclo" },

  "custom.map": { en: "Map", it: "Mappa" },
  "custom.mode": { en: "Mode", it: "Modalità" },
  "custom.score": { en: "Score limit", it: "Limite punteggio" },
  "custom.time": { en: "Time limit", it: "Limite tempo" },
  "custom.bots": { en: "Drills", it: "Drill" },
  "custom.weapons": { en: "Weapon pool", it: "Pool armi" },
  "custom.all": { en: "All weapons", it: "Tutte le armi" },
  "custom.abilities": { en: "Abilities", it: "Abilità" },
  "custom.ff": { en: "Friendly fire", it: "Fuoco amico" },
  "custom.move": { en: "Movement", it: "Movimento" },
  "custom.gravity": { en: "Gravity", it: "Gravità" },
  "custom.health": { en: "Health", it: "Salute" },
  "custom.regen": { en: "Regen delay", it: "Ritardo rigenerazione" },
  "custom.respawn": { en: "Respawn", it: "Rientro" },
  "custom.code": { en: "Invite code", it: "Codice invito" },
  "custom.create": { en: "Create private circuit", it: "Crea circuito privato" },
  "custom.join": { en: "Join code", it: "Entra con codice" },
  "custom.host": { en: "You host this circuit.", it: "Ospiti questo circuito." },
  "custom.local_only": { en: "Relay offline. This circuit stays on your machine.", it: "Nodo offline. Il circuito resta sulla tua macchina." },
  "custom.start": { en: "Start private", it: "Avvia privata" },

  "social.friends": { en: "Friends", it: "Amici" },
  "social.add": { en: "Add by code", it: "Aggiungi con codice" },
  "social.party": { en: "Party", it: "Gruppo" },
  "social.invite": { en: "Invite", it: "Invita" },
  "social.leave": { en: "Leave party", it: "Lascia il gruppo" },
  "social.mute": { en: "Mute", it: "Silenzia" },
  "social.block": { en: "Block", it: "Blocca" },
  "social.voice": { en: "Voice", it: "Voce" },
  "social.team_only": { en: "Team only", it: "Solo squadra" },
  "social.push": { en: "Push to talk", it: "Premi per parlare" },
  "social.mic": { en: "Microphone", it: "Microfono" },
  "social.mic_denied": { en: "Microphone permission was denied.", it: "Permesso microfono negato." },
  "social.code": { en: "Your code", it: "Il tuo codice" },
  "social.empty": { en: "No one on the list.", it: "Nessuno in lista." },

  "report.title": { en: "Report", it: "Segnala" },
  "report.cheating": { en: "Cheating", it: "Imbroglio" },
  "report.abusive": { en: "Abusive behavior", it: "Comportamento abusivo" },
  "report.exploiting": { en: "Exploiting", it: "Exploit" },
  "report.name": { en: "Inappropriate name", it: "Nome inappropriato" },
  "report.send": { en: "Send report", it: "Invia segnalazione" },
  "report.sent": { en: "Report filed with match telemetry.", it: "Segnalazione archiviata con la telemetria della partita." },
  "report.note": { en: "Optional note", it: "Nota opzionale" },

  "error.server_down": { en: "Dedicated relay is offline. Local circuits still run.", it: "Il nodo dedicato è offline. I circuiti locali funzionano." },
  "error.high_ping": { en: "Ping is too high for ranked. Pick a closer relay.", it: "Ping troppo alto per la classificata. Scegli un nodo più vicino." },
  "error.banned": { en: "This account is banned from the relay.", it: "Questo account è bandito dal nodo." },
  "error.full": { en: "That circuit is full.", it: "Quel circuito è pieno." },
  "error.invalid_name": { en: "Callsign must be 3–16 letters, numbers, or spaces.", it: "Il nominativo deve avere 3–16 lettere, numeri o spazi." },
  "error.credits": { en: "Not enough credits.", it: "Crediti insufficienti." },
  "error.owned": { en: "Already owned.", it: "Già posseduto." },
  "error.unknown_item": { en: "Unknown item.", it: "Oggetto sconosciuto." },
  "error.bad_code": { en: "Invite code not found.", it: "Codice invito non trovato." },
  "error.bad_packet": { en: "The relay rejected a packet.", it: "Il nodo ha rifiutato un pacchetto." },
  "error.unstable": { en: "Connection unstable.", it: "Connessione instabile." },
  "error.reconnect": { en: "Reconnecting…", it: "Riconnessione…" },
  "error.import": { en: "That file is not a Vectorbreak profile.", it: "Quel file non è un profilo Vectorbreak." },

  "tut.move": { en: "Move with WASD.", it: "Muoviti con WASD." },
  "tut.look": { en: "Move your mouse to look around. Right click aims; Esc pauses.", it: "Muovi il mouse per guardarti intorno. Clic destro mira; Esc mette in pausa." },
  "tut.sprint": { en: "Hold sprint and cross the lane.", it: "Tieni premuto lo scatto e attraversa la corsia." },
  "tut.jump": { en: "Jump.", it: "Salta." },
  "tut.slide": { en: "Sprint, then crouch, to drift.", it: "Scatta, poi accovacciati, per scivolare." },
  "tut.shoot": { en: "Break a target.", it: "Frattura un bersaglio." },
  "tut.aim": { en: "Aim and break a target.", it: "Mira e frattura un bersaglio." },
  "tut.reload": { en: "Reload.", it: "Ricarica." },
  "tut.switch": { en: "Switch weapons.", it: "Cambia arma." },
  "tut.ability": { en: "Use your tactic.", it: "Usa la tattica." },
  "tut.obj": { en: "Stand on the marked pad.", it: "Stai sul piedistallo segnato." },
  "tut.done": { en: "Deployment complete. The circuit is yours.", it: "Schieramento completo. Il circuito è tuo." },
  "tut.skip": { en: "Skip", it: "Salta" },

  "editor.title": { en: "Lattice editor", it: "Editor reticolo" },
  "editor.place": { en: "Click the ground to place. Right click deletes.", it: "Clicca il suolo per piazzare. Tasto destro elimina." },
  "editor.floor": { en: "Floor", it: "Pavimento" },
  "editor.wall": { en: "Wall", it: "Muro" },
  "editor.crate": { en: "Crate", it: "Cassa" },
  "editor.platform": { en: "Platform", it: "Piattaforma" },
  "editor.spawn_a": { en: "Spawn cyan", it: "Spawn ciano" },
  "editor.spawn_b": { en: "Spawn ember", it: "Spawn brace" },
  "editor.obj": { en: "Objective", it: "Obiettivo" },
  "editor.export": { en: "Export JSON", it: "Esporta JSON" },
  "editor.play": { en: "Playtest", it: "Prova" },
  "editor.saved": { en: "Lattice saved on this device.", it: "Reticolo salvato su questo dispositivo." },
  "editor.need": { en: "Add at least two spawns and one objective.", it: "Aggiungi almeno due spawn e un obiettivo." },
  "editor.clear": { en: "Clear", it: "Pulisci" },
  "editor.name": { en: "Lattice name", it: "Nome reticolo" },

  "replay.play": { en: "Play", it: "Play" },
  "replay.pause": { en: "Pause", it: "Pausa" },
  "replay.speed": { en: "Speed", it: "Velocità" },
  "replay.follow": { en: "Follow", it: "Segui" },
  "replay.free": { en: "Free camera", it: "Camera libera" },
  "replay.save": { en: "Download replay", it: "Scarica replay" },
  "replay.empty": { en: "No replay in memory. Finish a circuit.", it: "Nessun replay in memoria. Chiudi un circuito." },
  "replay.scrub": { en: "Scrub", it: "Scorri" },

  "season.s1.name": { en: "First Lattice", it: "Primo reticolo" },
  "season.s1.desc": { en: "A free track. New finishes, no sharper bullets.", it: "Un percorso gratuito. Nuove finiture, niente proiettili più affilati." },
  "season.track": { en: "Season track", it: "Percorso stagione" },
  "season.xp": { en: "Season XP", it: "XP stagione" },

  "net.warn": { en: "High latency. Hits still validate on the relay, inside a short rewind window.", it: "Latenza alta. I colpi si validano sul nodo, dentro una finestra di rewind corta." },
  "net.packet": { en: "Packet loss", it: "Perdita pacchetti" },
  "net.connected": { en: "Relay linked", it: "Nodo collegato" },
  "net.local": { en: "Simulating locally", it: "Simulazione locale" },
  "net.players": { en: "Players", it: "Giocatori" },
  "net.browser": { en: "Server browser", it: "Elenco server" },
  "net.join": { en: "Join", it: "Entra" },
  "net.capacity": { en: "Capacity", it: "Capacità" },

  "admin.title": { en: "Relay desk", it: "Banco del nodo" },
  "admin.reports": { en: "Reports", it: "Segnalazioni" },
  "admin.kick": { en: "Kick", it: "Espelli" },
  "admin.ban": { en: "Ban", it: "Bandisci" },
  "admin.mute": { en: "Mute", it: "Silenzia" },
  "admin.audit": { en: "Audit log", it: "Registro audit" },
  "admin.key": { en: "Admin key", it: "Chiave admin" },
  "admin.empty": { en: "No open reports.", it: "Nessuna segnalazione aperta." },

  "challenge.elims": { en: "Get {n} eliminations", it: "Ottieni {n} eliminazioni" },
  "challenge.heads": { en: "Land {n} headshots", it: "Piazza {n} colpi in testa" },
  "challenge.caps": { en: "Capture {n} objectives", it: "Cattura {n} obiettivi" },
  "challenge.wins": { en: "Win {n} circuits", it: "Vinci {n} circuiti" },
  "challenge.damage": { en: "Deal {n} damage", it: "Infliggi {n} danni" },
  "challenge.slides": { en: "Get {n} drift eliminations", it: "Ottieni {n} eliminazioni in scivolata" },
  "challenge.week_wins": { en: "Win {n} circuits this week", it: "Vinci {n} circuiti questa settimana" },
  "challenge.week_elims": { en: "Get {n} eliminations this week", it: "Ottieni {n} eliminazioni questa settimana" },
  "challenge.week_obj": { en: "Score {n} objective points", it: "Fai {n} punti obiettivo" },
  "challenge.week_modes": { en: "Play {n} different modes", it: "Gioca {n} modalità diverse" },
  "challenge.week_class": { en: "Get {n} eliminations with {class}", it: "Ottieni {n} eliminazioni con {class}" },

  "how.1": { en: "WASD move · Shift sprint · Ctrl drift · Space jump", it: "WASD muovi · Maiusc scatta · Ctrl scivola · Spazio salta" },
  "how.2": { en: "Mouse look · LMB fire · RMB aim · R reload · V melee", it: "Mouse guarda · LMB fuoco · RMB mira · R ricarica · V mischia" },
  "how.3": { en: "Q tactic · Z ultimate · Alt dodge · C shoulder · F interact", it: "Q tattica · Z ultra · Alt schivata · C spalla · F interagisci" },
  "how.4": { en: "Drills fill empty seats. They path, flank, and miss.", it: "I Drill riempiono i posti vuoti. Percorrono, aggirano e sbagliano." },

  "cos.default": { en: "Issue", it: "D'ordinanza" },
  "cos.ash_circuit": { en: "Ash Circuit", it: "Circuito cenere" },
  "cos.tide_mesh": { en: "Tide Mesh", it: "Maglia marea" },
  "cos.violet_seam": { en: "Violet Seam", it: "Cucitura viola" },
  "cos.paper_white": { en: "Paper White", it: "Bianco carta" },
  "cos.night_orchard": { en: "Night Orchard", it: "Frutteto notte" },
  "cos.factory": { en: "Factory", it: "Fabbrica" },
  "cos.stripe": { en: "Stripe", it: "Striscia" },
  "cos.honeycomb": { en: "Honeycomb", it: "Nido d'ape" },
  "cos.frost": { en: "Frost", it: "Brina" },
  "cos.ember": { en: "Ember", it: "Brace" },
  "cos.signal": { en: "Signal", it: "Segnale" },
  "cos.wave": { en: "Wave", it: "Saluto" },
  "cos.salute": { en: "Salute", it: "Saluto militare" },
  "cos.clap": { en: "Clap", it: "Applauso" },
  "cos.inspect": { en: "Inspect", it: "Ispeziona" },
  "cos.blank": { en: "Blank", it: "Vuoto" },
  "cos.chevron": { en: "Chevron", it: "Gallone" },
  "cos.split": { en: "Split", it: "Taglio" },
  "cos.orbit": { en: "Orbit", it: "Orbita" },
  "cos.lattice": { en: "Lattice", it: "Reticolo" },
  "cos.shard": { en: "Shard", it: "Scheggia" },
  "cos.ring": { en: "Ring", it: "Anello" },
  "cos.column": { en: "Column", it: "Colonna" },
  "cos.bracket": { en: "Bracket", it: "Parentesi" },
  "cos.dot": { en: "Dot", it: "Punto" },
  "cos.chevron_ch": { en: "Chevron", it: "Gallone" },
  "cos.circle": { en: "Circle", it: "Cerchio" },
  "cos.hash": { en: "Hash", it: "Griglia" },

  "ach.cat.combat": { en: "Combat", it: "Combattimento" },
  "ach.cat.movement": { en: "Movement", it: "Movimento" },
  "ach.cat.objectives": { en: "Objectives", it: "Obiettivi" },
  "ach.cat.weapons": { en: "Weapons", it: "Armi" },
  "ach.cat.ranked": { en: "Ranked", it: "Classificata" },
  "ach.cat.exploration": { en: "Exploration", it: "Esplorazione" },
  "ach.cat.social": { en: "Social", it: "Social" },
  "ach.cat.mastery": { en: "Mastery", it: "Maestria" },

  "ach.first_fracture.name": { en: "First Fracture", it: "Prima frattura" },
  "ach.first_fracture.desc": { en: "Eliminate an opponent.", it: "Elimina un avversario." },
  "ach.hot_circuit.name": { en: "Hot Circuit", it: "Circuito caldo" },
  "ach.hot_circuit.desc": { en: "Five eliminations in one circuit.", it: "Cinque eliminazioni in un circuito." },
  "ach.relentless.name": { en: "Relentless", it: "Incessante" },
  "ach.relentless.desc": { en: "Ten eliminations in one circuit.", it: "Dieci eliminazioni in un circuito." },
  "ach.breaker.name": { en: "Breaker", it: "Spezzatore" },
  "ach.breaker.desc": { en: "Twenty eliminations in one circuit.", it: "Venti eliminazioni in un circuito." },
  "ach.century.name": { en: "Century", it: "Centuria" },
  "ach.century.desc": { en: "100 lifetime eliminations.", it: "100 eliminazioni totali." },
  "ach.thousand_cuts.name": { en: "Thousand Cuts", it: "Mille tagli" },
  "ach.thousand_cuts.desc": { en: "1000 lifetime eliminations.", it: "1000 eliminazioni totali." },
  "ach.clean_head.name": { en: "Clean Head", it: "Testa pulita" },
  "ach.clean_head.desc": { en: "Land a headshot.", it: "Piazza un colpo in testa." },
  "ach.marksman_eye.name": { en: "Survey Eye", it: "Occhio di rilievo" },
  "ach.marksman_eye.desc": { en: "Eight headshots in one circuit.", it: "Otto colpi in testa in un circuito." },
  "ach.surgeon.name": { en: "Surgeon", it: "Chirurgo" },
  "ach.surgeon.desc": { en: "Half your eliminations as headshots, minimum eight.", it: "Metà eliminazioni in testa, minimo otto." },
  "ach.assist_engine.name": { en: "Assist Engine", it: "Motore assist" },
  "ach.assist_engine.desc": { en: "Eight assists in one circuit.", it: "Otto assist in un circuito." },
  "ach.untouchable.name": { en: "Untouched", it: "Intatto" },
  "ach.untouchable.desc": { en: "Win a circuit with zero deaths and five eliminations.", it: "Vinci un circuito senza morire e con cinque eliminazioni." },
  "ach.close_call.name": { en: "Close Call", it: "Per un soffio" },
  "ach.close_call.desc": { en: "Eliminate someone while under 22 health.", it: "Elimina qualcuno sotto i 22 di salute." },
  "ach.revenge.name": { en: "Return Signal", it: "Segnale di ritorno" },
  "ach.revenge.desc": { en: "Eliminate the operator who last fractured you.", it: "Elimina chi ti ha fratturato per ultimo." },
  "ach.multi_break.name": { en: "Multi Break", it: "Multi frattura" },
  "ach.multi_break.desc": { en: "Three eliminations within eight seconds.", it: "Tre eliminazioni in otto secondi." },
  "ach.shutdown.name": { en: "Shutdown", it: "Spegnimento" },
  "ach.shutdown.desc": { en: "Eliminate someone during your ultimate.", it: "Elimina qualcuno durante la tua ultra." },
  "ach.melee_break.name": { en: "Close Punctuation", it: "Punteggiatura corta" },
  "ach.melee_break.desc": { en: "Eliminate with a melee weapon.", it: "Elimina con un'arma da mischia." },
  "ach.long_shot.name": { en: "Long Line", it: "Linea lunga" },
  "ach.long_shot.desc": { en: "Eliminate beyond 40 meters.", it: "Elimina oltre i 40 metri." },
  "ach.point_blank.name": { en: "Point Blank", it: "A bruciapelo" },
  "ach.point_blank.desc": { en: "Shotgun elimination under 4 meters.", it: "Eliminazione con canna liscia sotto i 4 metri." },
  "ach.first_drift.name": { en: "First Drift", it: "Prima scivolata" },
  "ach.first_drift.desc": { en: "Drift.", it: "Scivola." },
  "ach.slide_break.name": { en: "Drift Break", it: "Frattura in scivolata" },
  "ach.slide_break.desc": { en: "Eliminate while drifting.", it: "Elimina mentre scivoli." },
  "ach.drift_jump.name": { en: "Drift Jump", it: "Salto dalla scivolata" },
  "ach.drift_jump.desc": { en: "Jump out of a drift.", it: "Salta da una scivolata." },
  "ach.wallrunner.name": { en: "Wall Kick", it: "Calcio al muro" },
  "ach.wallrunner.desc": { en: "Wall-kick eight times in one circuit.", it: "Dai otto calci al muro in un circuito." },
  "ach.vault_cadet.name": { en: "Vault Cadet", it: "Cadetto scavalco" },
  "ach.vault_cadet.desc": { en: "Vault an obstacle.", it: "Scavalca un ostacolo." },
  "ach.airtime.name": { en: "Airtime", it: "Tempo in aria" },
  "ach.airtime.desc": { en: "Spend 18 seconds airborne in one circuit.", it: "Passa 18 secondi in aria in un circuito." },
  "ach.dodge_artist.name": { en: "Dodge Artist", it: "Artista della schivata" },
  "ach.dodge_artist.desc": { en: "Dodge twelve times in one circuit.", it: "Schiva dodici volte in un circuito." },
  "ach.speed_circuit.name": { en: "Speed Circuit", it: "Circuito veloce" },
  "ach.speed_circuit.desc": { en: "Travel 1400 meters in one circuit.", it: "Percorri 1400 metri in un circuito." },
  "ach.chain_drift.name": { en: "Long Drift", it: "Scivolata lunga" },
  "ach.chain_drift.desc": { en: "Hold a single drift for 12 meters.", it: "Tieni una scivolata per 12 metri." },
  "ach.zone_taken.name": { en: "Zone Taken", it: "Zona presa" },
  "ach.zone_taken.desc": { en: "Capture an objective.", it: "Cattura un obiettivo." },
  "ach.holder.name": { en: "Holder", it: "Presidio" },
  "ach.holder.desc": { en: "Stand on objectives for 30 seconds in one circuit.", it: "Stai sugli obiettivi per 30 secondi in un circuito." },
  "ach.core_thief.name": { en: "Core Thief", it: "Ladro di nuclei" },
  "ach.core_thief.desc": { en: "Steal a core.", it: "Ruba un nucleo." },
  "ach.core_home.name": { en: "Core Home", it: "Nucleo a casa" },
  "ach.core_home.desc": { en: "Return a stolen core.", it: "Riporta un nucleo rubato." },
  "ach.defender.name": { en: "Defender", it: "Difensore" },
  "ach.defender.desc": { en: "Five defensive eliminations in one circuit.", it: "Cinque eliminazioni difensive in un circuito." },
  "ach.objective_first.name": { en: "Objective First", it: "Prima l'obiettivo" },
  "ach.objective_first.desc": { en: "Finish with the highest objective score.", it: "Chiudi con il punteggio obiettivi più alto." },
  "ach.triple_hold.name": { en: "Triple Hold", it: "Triplo presidio" },
  "ach.triple_hold.desc": { en: "Your team holds every Dominion zone at once.", it: "La tua squadra tiene tutte le zone Dominio insieme." },
  "ach.last_one.name": { en: "Last One", it: "L'ultimo" },
  "ach.last_one.desc": { en: "Win a Last Circuit round as the only one standing.", it: "Vinci un round di Ultimo circuito da solo in piedi." },
  "ach.polymath.name": { en: "Polymath", it: "Polimate" },
  "ach.polymath.desc": { en: "Eliminate with eight different weapons.", it: "Elimina con otto armi diverse." },
  "ach.arsenal_complete.name": { en: "March Complete", it: "Marcia completa" },
  "ach.arsenal_complete.desc": { en: "Win Arsenal March.", it: "Vinci la Marcia dell'arsenale." },
  "ach.attachment_tuner.name": { en: "Tuner", it: "Accordatore" },
  "ach.attachment_tuner.desc": { en: "Equip a full attachment set.", it: "Equipaggia un set completo di accessori." },
  "ach.experimental_taste.name": { en: "Odd Taste", it: "Gusto strano" },
  "ach.experimental_taste.desc": { en: "Eliminate with an experimental weapon.", it: "Elimina con un'arma sperimentale." },
  "ach.iron_sidearm.name": { en: "Iron Sidearm", it: "Secondaria di ferro" },
  "ach.iron_sidearm.desc": { en: "Five pistol eliminations in one circuit.", it: "Cinque eliminazioni con pistola in un circuito." },
  "ach.glass_maker.name": { en: "Glass Maker", it: "Vetraio" },
  "ach.glass_maker.desc": { en: "Break ten glass panels.", it: "Rompi dieci pannelli di vetro." },
  "ach.furnace_operator.name": { en: "Furnace Hand", it: "Mano alla fornace" },
  "ach.furnace_operator.desc": { en: "Deal 400 damage with LMGs in one circuit.", it: "Infliggi 400 danni con mitragliatrici in un circuito." },
  "ach.one_mag.name": { en: "One Cell", it: "Una cella" },
  "ach.one_mag.desc": { en: "Three eliminations without reloading.", it: "Tre eliminazioni senza ricaricare." },
  "ach.placed.name": { en: "Placed", it: "Piazzato" },
  "ach.placed.desc": { en: "Finish placement matches.", it: "Completa le partite di piazzamento." },
  "ach.signal_rank.name": { en: "Signal Rank", it: "Grado segnale" },
  "ach.signal_rank.desc": { en: "Reach Signal.", it: "Raggiungi Segnale." },
  "ach.apex_rank.name": { en: "Apex Rank", it: "Grado apice" },
  "ach.apex_rank.desc": { en: "Reach Apex.", it: "Raggiungi Apice." },
  "ach.singularity.name": { en: "Singularity", it: "Singolarità" },
  "ach.singularity.desc": { en: "Reach Singularity.", it: "Raggiungi Singolarità." },
  "ach.promotion.name": { en: "Promotion", it: "Promozione" },
  "ach.promotion.desc": { en: "Rank up.", it: "Sali di grado." },
  "ach.comeback.name": { en: "Comeback Circuit", it: "Circuito di rimonta" },
  "ach.comeback.desc": { en: "Win after trailing by a wide margin.", it: "Vinci dopo essere stati largamente sotto." },
  "ach.cartographer.name": { en: "Cartographer", it: "Cartografo" },
  "ach.cartographer.desc": { en: "Play eight different lattices.", it: "Gioca otto reticoli diversi." },
  "ach.night_market.name": { en: "Night Market", it: "Mercato di notte" },
  "ach.night_market.desc": { en: "Play Cinder Market.", it: "Gioca Mercato brace." },
  "ach.all_lattices.name": { en: "All Lattices", it: "Tutti i reticoli" },
  "ach.all_lattices.desc": { en: "Play every combat lattice.", it: "Gioca ogni reticolo da combattimento." },
  "ach.editor.name": { en: "Draftsman", it: "Disegnatore" },
  "ach.editor.desc": { en: "Save a custom lattice.", it: "Salva un reticolo personalizzato." },
  "ach.practice_makes.name": { en: "Calibration", it: "Calibrazione" },
  "ach.practice_makes.desc": { en: "Spend five minutes in the bay.", it: "Passa cinque minuti nella baia." },
  "ach.party_up.name": { en: "Party Up", it: "In gruppo" },
  "ach.party_up.desc": { en: "Queue with a party.", it: "Mettiti in coda con un gruppo." },
  "ach.teammate.name": { en: "Teammate", it: "Compagno" },
  "ach.teammate.desc": { en: "Play ten circuits with a friend on the list.", it: "Gioca dieci circuiti con un amico in lista." },
  "ach.quick_talker.name": { en: "Quick Talker", it: "Parlatore rapido" },
  "ach.quick_talker.desc": { en: "Use quick chat twenty times.", it: "Usa la chat rapida venti volte." },
  "ach.commend.name": { en: "Good Signal", it: "Buon segnale" },
  "ach.commend.desc": { en: "Commend another operator.", it: "Elogia un altro operatore." },
  "ach.operator_loyal.name": { en: "Loyal", it: "Fedele" },
  "ach.operator_loyal.desc": { en: "Play 15 circuits with one operator.", it: "Gioca 15 circuiti con un operatore." },
  "ach.weapon_bond.name": { en: "Weapon Bond", it: "Legame con l'arma" },
  "ach.weapon_bond.desc": { en: "Reach weapon level 5.", it: "Raggiungi il livello arma 5." },
  "ach.max_loadout.name": { en: "Four Kits", it: "Quattro kit" },
  "ach.max_loadout.desc": { en: "Keep four kits ready.", it: "Tieni pronti quattro kit." },
  "ach.seasoned.name": { en: "Seasoned", it: "Esperto" },
  "ach.seasoned.desc": { en: "Reach account level 10.", it: "Raggiungi il livello account 10." },
  "ach.veteran.name": { en: "Veteran", it: "Veterano" },
  "ach.veteran.desc": { en: "Reach account level 25.", it: "Raggiungi il livello account 25." },
  "ach.challenge_hunter.name": { en: "Challenge Hunter", it: "Cacciatore di sfide" },
  "ach.challenge_hunter.desc": { en: "Complete 10 challenges.", it: "Completa 10 sfide." },
  "ach.flawless_round.name": { en: "Flawless Round", it: "Round impeccabile" },
  "ach.flawless_round.desc": { en: "Win a Last Circuit round without a death on your team.", it: "Vinci un round di Ultimo circuito senza morti in squadra." },
  "ach.tutorial_grad.name": { en: "Deployed", it: "Schierato" },
  "ach.tutorial_grad.desc": { en: "Finish the tutorial.", it: "Completa il tutorial." },
  "ach.spectator.name": { en: "Gallery", it: "Galleria" },
  "ach.spectator.desc": { en: "Spectate for 30 seconds.", it: "Osserva per 30 secondi." },
  "ach.replay_watcher.name": { en: "Echo", it: "Eco" },
  "ach.replay_watcher.desc": { en: "Watch a replay.", it: "Guarda un replay." },

  "kit.hitscan": { en: "Hitscan", it: "Colpo istantaneo" },
  "kit.projectile": { en: "Projectile", it: "Proiettile" },
  "set.ch.cross": { en: "Cross", it: "Croce" },
  "set.ch.circle": { en: "Circle", it: "Cerchio" },
  "set.ch.bracket": { en: "Bracket", it: "Parentesi" },
  "set.ch.chevron": { en: "Chevron", it: "Gallone" },
  "set.ch.hash": { en: "Hash", it: "Griglia" },
  "admin.dismiss": { en: "Dismiss", it: "Archivia" },
  "custom.hosted": { en: "Invite code {code}", it: "Codice invito {code}" }
};

export function createI18n(lang = 'en') {
  return {
    lang: lang === 'it' ? 'it' : 'en',
    t(key, vars) {
      const row = STRINGS[key];
      let s = row ? (row[this.lang] || row.en || key) : key;
      if (vars) {
        for (const [k, v] of Object.entries(vars)) s = s.replaceAll(`{${k}}`, String(v));
      }
      return s;
    },
    set(lang) {
      this.lang = lang === 'it' ? 'it' : 'en';
    },
    has(key) {
      return !!STRINGS[key];
    },
  };
}

export function allKeys() {
  return Object.keys(STRINGS);
}
